### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by Suburbanno** [Its-Haze/league-rpc#64]
```bash
Exception in thread Thread-25:
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-26:
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 1401, in run
  File "threading.py", line 1401, in run
  File "league_rpc\models\rpc_updater.py", line 82, in update_rpc_and_reset_flag
  File "league_rpc\models\rpc_updater.py", line 82, in update_rpc_and_reset_flag
  File "league_rpc\models\rpc_updater.py", line 329, in update_rpc
  File "league_rpc\models\rpc_updater.py", line 329, in update_rpc
  File "league_rpc\models\rpc_updater.py", line 150, in in_lobby_rpc
  File "league_rpc\models\rpc_updater.py", line 150, in in_lobby_rpc
  File "pypresence\presence.py", line 34, in update
  File "pypresence\presence.py", line 34, in update
  File "nest_asyncio.py", line 99, in run_until_complete
  File "nest_asyncio.py", line 99, in run_until_complete
  File "asyncio\futures.py", line 203, in result
  File "asyncio\tasks.py", line 277, in __step
  File "asyncio\futures.py", line 203, in result
  File "pypresence\baseclient.py", line 86, in read_output
  File "asyncio\tasks.py", line 277, in __step
  File "json\__init__.py", line 346, in loads
  File "pypresence\baseclient.py", line 86, in read_output
  File "json\decoder.py", line 337, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 4: invalid continuation byte
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

![image](https://github.com/user-attachments/assets/1ce8af81-3fff-4208-a3fc-d1e89cbe5597)

**Comment by Its-Haze** [comment]
I think i saw this error once as well, but i have been unable to reproduce it.

Does it happen all the time for you?
Does it happen after a certain action or event?

Usually a restart of leagueRPC fixes the issue (you do not need to close the league client when you restart leagueRPC)

**Comment by Suburbanno** [comment]
> I think i saw this error once as well, but i have been unable to reproduce it.
> 
> Does it happen all the time for you? Does it happen after a certain action or event?
> 
> Usually a restart of leagueRPC fixes the issue (you do not need to close the league client when you restart leagueRPC)

Ok, let's go

this error happened several times in different games.
example:

1 - When opening for the first time, I had to restart the PC
2 - When starting the first game
3 - When playing ARAM

I had to restart twice so that the error wouldn't happen again. So far it's ok, I don't know what caused it

**Comment by Its-Haze** [comment]
I will try and see if i can reproduce it. As far as i know, i have not gotten this error consistently.

**Comment by Suburbanno** [comment]
> I will try and see if i can reproduce it. As far as i know, i have not gotten this error consistently.

I just got the error again after a few hours of use
![image](https://github.com/user-attachments/assets/faa897ba-d78e-48c1-b876-6319222376ec)

@Its-Haze

**Comment by Its-Haze** [comment]
@Suburbanno `v3.1.0` is now released with a fix that i believe should make this issue dissapear. Please let me know if it works better for you after downloading the newer version :)

**Comment by Suburbanno** [comment]
@Its-Haze :(

```bash
INFO: Connected to Discord RPC!
TASK: Checking Discord... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO: Connected to the League Client API.
INFO: Successfully gathered base data.
INFO: Discord RPC successfully updated
TASK: Start LeagueRPC Engine... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO: LeagueRPC is ready!
INFO: Disconnected from the League Client API.
Exception in thread Thread-4 (start_connector):
Traceback (most recent call last):
  File "lcu_driver\connection.py", line 187, in run_ws
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 344, in decode
  File "json\decoder.py", line 362, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1041, in _bootstrap_inner
  File "threading.py", line 992, in run
  File "league_rpc\lcu_api\lcu_connector.py", line 272, in start_connector
  File "lcu_driver\connector.py", line 70, in start
  File "lcu_driver\connector.py", line 64, in wrapper
  File "nest_asyncio.py", line 99, in run_until_complete
  File "asyncio\futures.py", line 200, in result
  File "asyncio\tasks.py", line 304, in __step_run_and_handle_result
  File "lcu_driver\connection.py", line 72, in init
  File "lcu_driver\connection.py", line 190, in run_ws
  File "logging\__init__.py", line 1531, in warning
  File "logging\__init__.py", line 1664, in _log
  File "logging\__init__.py", line 1680, in handle
  File "logging\__init__.py", line 1736, in callHandlers
  File "logging\__init__.py", line 1026, in handle
  File "rich\logging.py", line 128, in emit
  File "logging\__init__.py", line 998, in format
  File "logging\__init__.py", line 711, in format
  File "logging\__init__.py", line 400, in getMessage
TypeError: not all arguments converted during string formatting
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000027FA9FE1090>
```

**Comment by Its-Haze** [comment]
@Suburbanno And you're using the latest version?
I will need more information

1. do you have any specific arguments for leaguerpc?
2. What language is your league client on?
3. does this happen right on start (when you are in the client) or does this occur when you click on something?

**Comment by Suburbanno** [comment]
> @Suburbanno And you're using the latest version? I will need more information
> 
> 1. do you have any specific arguments for leaguerpc?
> 2. What language is your league client on?
> 3. does this happen right on start (when you are in the client) or does this occur when you click on something?

Let's go.
1. I downloaded the new version
2. I opened Discord
3. I ran LeagueRPC
4. The LOL client was opened and the error was generated.

My client language is in English, I'm not using any arguments and the only clicks I made were to enter the password and username for the LOL client.

**Comment by Its-Haze** [comment]
Will try to look into it.

**Comment by Its-Haze** [comment]
@Suburbanno I've created one file for debugging purposes, and another file that increases the websocket limit from 8mb to 64. please start off by testing the first (debugging) file and if errors occur, please send me the full responses so that i can investigate.

just for testing purposes as well, i added a 64mb version, so please try that as well and see if that also crashes.

Debugging with 8mb: [leagueRPC-custom8mb.exe](https://github.com/Its-Haze/league-rpc/releases/download/v3.1.0/leagueRPC-custom8mb.exe)
Debugging with 64mb: [leagueRPC-custom64mb.exe](https://github.com/Its-Haze/league-rpc/releases/download/v3.1.0/leagueRPC-custom64mb.exe)

The point of these custom debugging files i send here is not to be the "finished" application, but only meant to help me investigate your issue better. Cause i am not able to reproduce your exact issue, and i hope to see some more logs that might indicate what's going on.

**Comment by Its-Haze** [comment]
If the application crashes, please open a terminal and run the executable in the terminal to preserve the logs, let me know if you need help

**Comment by Suburbanno** [comment]
> @Suburbanno I've created one file for debugging purposes, and another file that increases the websocket limit from 8mb to 64. please start off by testing the first (debugging) file and if errors occur, please send me the full responses so that i can investigate.
> 
> just for testing purposes as well, i added a 64mb version, so please try that as well and see if that also crashes.
> 
> Debugging with 8mb: [leagueRPC-custom8mb.exe](https://github.com/Its-Haze/league-rpc/releases/download/v3.1.0/leagueRPC-custom8mb.exe) Debugging with 64mb: [leagueRPC-custom64mb.exe](https://github.com/Its-Haze/league-rpc/releases/download/v3.1.0/leagueRPC-custom64mb.exe)
> 
> The point of these custom debugging files i send here is not to be the "finished" application, but only meant to help me investigate your issue better. Cause i am not able to reproduce your exact issue, and i hope to see some more logs that might indicate what's going on.


my antivirus is accusing it as a trojan
![image](https://github.com/user-attachments/assets/818f4ed2-e832-4fac-a669-5b040a750f92)

![image](https://github.com/user-attachments/assets/68cb2497-4785-435f-9d26-b884d1983634)

**Comment by Suburbanno** [comment]
maybe a false positive from windows defender

**Comment by Its-Haze** [comment]
ye, antivirus programs will most likely flag these files as viruses since they check running processes, connect to discord and league, and other things that automatically trigger antivirus's.

If you want to rather build it from source and test it like that, i am happy to walk you through it

**Comment by Suburbanno** [comment]
@Its-Haze  It's funny, I tested both versions and no error was shown, it worked normally, just a lot of slowness in "TASK: Start LeagueRPC engine...", about 5 minutes in each version.

I tested the last stable version again and the error changed, only this one is shown:

```bash
INFO: League client is running!
TASK: Checking League... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO: Checking if Discord is running...
INFO: Discord is running!
INFO: Connected to Discord RPC!
TASK: Checking Discord... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO: Connected to the League Client API.
INFO: TFT Companion data updated.
INFO: Successfully gathered base data.
INFO: Discord RPC successfully updated
TASK: Start LeagueRPC Engine... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO: LeagueRPC is ready!
INFO: Game is starting. Good luck!
WARNING: Unhandled Gameflow Phase: TerminatedInError
```

**Comment by Its-Haze** [comment]
The stable version is running on 8mb, it just doesn't have the debug log i added. So i was hoping to see the error there, atleast..
But if none of them give you this error, then i would suggest to keep using the "8mb debug" version until you get the same issue again, and then you can update this ticket if anything does show up. 

I also noticed that the leagueRPC task takes longer than before.. i will look into that as well.

Removing the 8mb/64mb downloadables from the releases page, as they were only intended for debugging this issue, and i don't want to confuse others of what to download.

**Comment by Its-Haze** [comment]
oh and the `WARNING: Unhandled Gameflow Phase: TerminatedInError` is interesting, but i think that can safely be ignored.

**Comment by Its-Haze** [comment]
Hi. Are you still experiencing similar issues?

**Comment by Suburbanno** [comment]
> Hi. Are you still experiencing similar issues?

No, everything is ok!
